[package]
name = "nimble-gui"
version = "0.0.0"
edition = "2021"

[dependencies]
nimble = { path = "lib/nimble" }
eframe = "0.22.0"
egui = "0.22.0"

[build-dependencies]
cc = "1.0"

[[bin]]
name = "nimble-gui"
path = "src/main.rs"